title: "Molly McMahon"
description: "todo some actual description"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-remote-theme # make sure this is included
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

header:
  nav:
    - text: "Home"
      url: "/"
    - text: "Blog"
      url: "/blog/"
    - text: "About"
      url: "/about/"
    - text: "Contact"
      url: "/contact/"



